name: Static Checks

on: [pull_request]

jobs:
  static-check:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
      with:
        path: src/github.com/aws/amazon-ecs-agent
    - name: run static checks
      run: |
        pwd
        cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
        echo '${{ github.event.pull_request.head.sha }}'
        echo ${GOPATH}
        echo al2-integ-${{ github.event.pull_request.head.sha }}
        echo al2-integ-'${{ github.event.pull_request.head.sha }}'
        echo ${GOROOT}
        make get-deps
        make static-check
      env:
        GOPATH: /home/runner/work/amazon-ecs-agent/amazon-ecs-agent

  x-platform-build:
    name: Cross platform build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: src/github.com/aws/amazon-ecs-agent
    - name: make xplatform-build
      run: |
        export GOPATH=$GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
        make xplatform-build
